### ISSUE TITLE
Echo command doesnt show any results

### ISSUE THREAD

**Issue by nisarnabeel** [IMDEANetworksWNG/Mikrotik-researcher-tools#1]
I installed openwrt on two WAP 60G x3 devices and set up iperf between the two, the two devices communciate on wireless interface wlan0, and when i issue following ommand
echo -n -e '\x08\x55\x31\x0a\xd6\xe0' | iw dev wlan0 vendor recv 0x001374 0x81 -
on the STA, changing the MAC address to the AP one, the command is executed, however i cant see any results. Same  happens with another echo command.

**Comment by AbhiGulia** [comment]
For some reason the echo command doesn't print results directly but if we use dmesg command after the echo command, we can see the results printed there.
